//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservation.Models
{
    using HotelReservation.DAL;
    using HotelReservation.HelperCodes.Codes;
    using System;
    using System.Collections.Generic;

    public partial class CUSTOMER_PROFILE
    {
        DataAccess da;
        public System.Guid CUST_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string PHONE_NO { get; set; }
        public string GENDER { get; set; }
        public string STATUS { get; set; }
        public string PASSWORD { get; set; }

        public string CONFIRMPASSWORD { get; set; }

        public PartialLogin extraLogin = new PartialLogin();

        internal bool CustomerSignUp()
        {
            da = new DataAccess();
            bool isLoginSuccessful = false;
            try {

                CUSTOMER_PROFILE Profile = new CUSTOMER_PROFILE();
                Profile.CUST_ID = Guid.NewGuid();
                Profile.FIRST_NAME = this.FIRST_NAME;
                Profile.LAST_NAME = this.LAST_NAME;
                Profile.GENDER = this.GENDER;
                Profile.ADDRESS = this.ADDRESS;
                Profile.EMAIL = this.EMAIL;
                Profile.PHONE_NO = this.PHONE_NO;
                Profile.PASSWORD = this.PASSWORD;
                Profile.CONFIRMPASSWORD = this.CONFIRMPASSWORD;
                Profile.STATUS = this.STATUS;

                isLoginSuccessful = da.CustomerSignUp(Profile);

                if (isLoginSuccessful)
                {
                    SessionUser user = new SessionUser()
                    {
                        UserID = Profile.CUST_ID,
                        FirstName = Profile.FIRST_NAME,
                        LastName = Profile.LAST_NAME,
                        Email = Profile.EMAIL,
                        PhoneNo = Profile.PHONE_NO,
                        Status = Profile.STATUS
                    };

                    SessionHandler.User = user;
                    SessionHandler.AddToCookie(user);
                }
            
            }
            catch
            {
                isLoginSuccessful = false;

            }
            return isLoginSuccessful;
            
        }

        public CUSTOMER_PROFILE CustomerDetails(Guid custID)
        {
            da = new DataAccess();
            return da.CustomerDetails(custID);
        }

        public CUSTOMER_PROFILE CustomerLogin()
        {
            da = new DataAccess();
            CUSTOMER_PROFILE profile = da.CustomerLogin(this.EMAIL, this.PASSWORD);

            if (profile != null)
            {
                SessionUser user = new SessionUser()
                {
                    UserID = profile.CUST_ID,
                    FirstName = profile.FIRST_NAME,
                    LastName = profile.LAST_NAME,
                    PhoneNo = profile.PHONE_NO,
                    Email = profile.EMAIL,
                    Status = profile.STATUS
                };

                SessionHandler.User = user;
                SessionHandler.AddToCookie(user);
            }
            return profile;
        }

        public bool customerUpdate()
        {
            CUSTOMER_PROFILE updateCustomer = new CUSTOMER_PROFILE();

            updateCustomer.CUST_ID = this.CUST_ID;
            updateCustomer.FIRST_NAME = this.FIRST_NAME;
            updateCustomer.LAST_NAME = this.LAST_NAME;
            updateCustomer.GENDER = this.GENDER;
            updateCustomer.ADDRESS = this.ADDRESS;
            updateCustomer.PHONE_NO = this.PHONE_NO;
            updateCustomer.EMAIL = this.EMAIL;
            updateCustomer.PASSWORD = this.PASSWORD;

            da = new DataAccess();
            return da.CustomerUpdate(updateCustomer);
        }
    }
}
