//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservation.Models
{
    using HotelReservation.DAL;
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION
    {
        DataAccess da;

        public System.Guid RESERVE_ID { get; set; }
        public Nullable<System.Guid> PAYMENT_ID { get; set; }
        public System.Guid CUST_ID { get; set; }
        public System.DateTime ARRIVAL_DATE { get; set; }
        public System.DateTime DEPARTURE_DATE { get; set; }
        public string BOOKING_STATUS { get; set; }
        public string ROOM_ID { get; set; }

        internal bool Booking()
        {
            da = new DataAccess();
            bool isReserveSuccesful = false;

            try
            {
                RESERVATION bookroom = new RESERVATION();

                bookroom.RESERVE_ID = this.RESERVE_ID;
                bookroom.CUST_ID = this.CUST_ID;
                bookroom.ARRIVAL_DATE = this.ARRIVAL_DATE;
                bookroom.DEPARTURE_DATE = this.DEPARTURE_DATE;
                bookroom.ROOM_ID = this.ROOM_ID;

                isReserveSuccesful = da.Booking(bookroom);             
            }
            catch (Exception)
            {
                isReserveSuccesful = false;
            }

            return isReserveSuccesful;
        }

    }
}
