//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM_TYPE_INFO
    {
        public ROOM_TYPE_INFO()
        {
            this.ROOM_DETAILS = new HashSet<ROOM_DETAILS>();
        }
    
        public string ROOM_TYPE { get; set; }
        public decimal ROOM_PRICE { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal MAX_GUEST { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
    
        public virtual ICollection<ROOM_DETAILS> ROOM_DETAILS { get; set; }
    }
}
